require.config({
  shim: {

  },
  paths: {
    angular: "bower_components/angular/angular",
    "angular-bootstrap": "bower_components/angular-bootstrap/ui-bootstrap-tpls",
    "angular-cookies": "bower_components/angular-cookies/angular-cookies",
    "angular-hammer": "bower_components/angular-hammer/angular-hammer",
    "angular-hotkeys": "bower_components/angular-hotkeys/angular-hotkeys.min",
    "angular-mocks": "bower_components/angular-mocks/angular-mocks",
    "angular-resource": "bower_components/angular-resource/angular-resource",
    "angular-route": "bower_components/angular-route/angular-route",
    "angular-sanitize": "bower_components/angular-sanitize/angular-sanitize",
    "angular-scenario": "bower_components/angular-scenario/angular-scenario",
    "angular-socket-io": "bower_components/angular-socket-io/socket",
    "angular-touch": "bower_components/angular-touch/angular-touch",
    "angular-ui-ace": "bower_components/angular-ui-ace/ui-ace",
    "angular-ui-calendar": "bower_components/angular-ui-calendar/src/calendar",
    "angular-ui-codemirror": "bower_components/angular-ui-codemirror/ui-codemirror",
    "angular-ui-map": "bower_components/angular-ui-map/ui-map",
    "angular-ui-router": "bower_components/angular-ui-router/release/angular-ui-router",
    "angular-ui-tree": "bower_components/angular-ui-tree/dist/angular-ui-tree",
    "angular-ui-utils": "bower_components/angular-ui-utils/ui-utils",
    "angular-websocket": "bower_components/angular-websocket/angular-websocket",
    angularfire: "bower_components/angularfire/angularfire",
    bootstrap: "bower_components/bootstrap/dist/js/bootstrap",
    affix: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/affix",
    alert: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/alert",
    button: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/button",
    carousel: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/carousel",
    collapse: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/collapse",
    dropdown: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/dropdown",
    tab: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/tab",
    transition: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/transition",
    scrollspy: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/scrollspy",
    modal: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/modal",
    tooltip: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/tooltip",
    popover: "bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/popover",
    "createjs-preloadjs": "bower_components/createjs-preloadjs/lib/preloadjs-0.4.1.combined",
    "createjs-soundjs": "bower_components/createjs-soundjs/lib/soundjs-0.5.2.combined",
    "createjs-tweenjs": "bower_components/createjs-tweenjs/lib/tweenjs-0.5.1.combined",
    easeljs: "bower_components/easeljs/lib/easeljs-0.7.1.combined",
    "es5-shim": "bower_components/es5-shim/es5-shim",
    excanvas: "bower_components/excanvas/excanvas",
    "font-awesome": "bower_components/font-awesome/fonts/*",
    html5shiv: "bower_components/html5shiv/dist/html5shiv",
    jquery: "bower_components/jquery/dist/jquery",
    json3: "bower_components/json3/lib/json3",
    lodash: "bower_components/lodash/dist/lodash.compat",
    moment: "bower_components/moment/moment",
    "ng-grid": "bower_components/ng-grid/build/ng-grid",
    respond: "bower_components/respond/dest/respond.src"
  },
  packages: [

  ]
});
